blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# FOSUSerBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"