<?php

namespace BlogBundle\Repository;

/**
 * @author 	Alaa Attya <alaa.attya91@gmail.com>
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
}
