<?php

namespace BlogBundle\Repository;

/**
 * @author 	Alaa Attya <alaa.attya91@gmail.com>
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository {

	public function get_published_articles() {
		$published_poats = $this->getEntityManager()->getRepository('BlogBundle:PostStatus')->findOneByTitle("published")->getPosts();

		return $published_poats;
	}
}
